# Generated by Django 2.2.7 on 2019-11-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
