# Generated by Django 2.2.7 on 2019-11-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_usersinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='Adult',
            field=models.BooleanField(default=True),
        ),
    ]
