# Generated by Django 2.2.7 on 2019-11-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_usersinfo_adult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersinfo',
            name='Adult',
        ),
        migrations.RemoveField(
            model_name='usersinfo',
            name='age',
        ),
    ]
